name: Valgrind Cachegrind

on:
  pull_request:
    branches: [main]
jobs:
  valgrind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Install cg_annotate
        run: |
          sudo apt-get install -y kcachegrind

      - name: Run Valgrind
        run: |
          cargo b -r -p revm-test --bin snailtracer
          valgrind --tool=cachegrind target/release/snailtracer >> cachegrind_results.txt

      - name: Valgrind results
        id: valgrind_results
        run: |
          cat cachegrind_results.txt
          contents=$(<cachegrind_results.txt)
          printf "out=%s" "${contents//$'\n'/\\n}" >> "$GITHUB_OUTPUT"

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ```
                ${{ steps.valgrind_results.outputs.out }}
            ```
