name: Valgrind Cachegrind

on:
  pull_request:
    branches: [main]
jobs:
  valgrind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Install cg_annotate
        run: |
          sudo apt-get install -y kcachegrind

      - name: Run Valgrind
        run: |
          cargo b -r -p revm-test --bin snailtracer
          valgrind --tool=cachegrind target/release/snailtracer

          # Extract relevant information from cachegrind.out file
          cg_annotate cachegrind.out.* > cachegrind_results.txt

      - name: Valgrind results
        id: valgrind_results
        run: |
          cat cachegrind_results.txt
          contents=$(<cachegrind_results.txt)
          printf "out=%s" "${contents//$'\n'/\\n}" >> "$GITHUB_OUTPUT"
      
      - name: Setup cURL for filebin
        run: |
          sudo apt-get install -y curl
      
      - name: Upload to filebin
        id: filebin
        run: |
          random_hash=$(uuidgen | tr '[:upper:]' '[:lower:]' | tr -d '-')
          new_random_hash=$(echo $random_hash | cut -c1-8)
          bin_name=$(printf "revmfilebin-%s" "${new_random_hash}")
          name=$(printf "cachegrind_results-%s-%s.txt" "${GITHUB_SHA}" "${random_hash}")
          url=$(printf "https://filebin.net/")
          curl -X 'POST' \
          $url \
          -H bin: "$bin_name" \
          -H filename: "$name" \
          -H 'accept: application/json' \
          -H 'Content-Type: application/octet-stream' \
          --data-binary '@cachegrind_results.txt'

          echo "url_name=https://filebin.net/revmfilebin/$name" >> "$GITHUB_OUTPUT"

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            See the results of the Valgrind Cachegrind run [here](${{ steps.filebin.outputs.url_name }}) :file_folder: {:target="_blank"}.

            This link will expire in 6 days from now!

      


      
